name: esense
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  esense_flutter: ^0.2.0+2
  flame: ^0.17.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: SigmarOne-Regular
      fonts:
        - asset: assets/fonts/SigmarOne-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/Menu/b_Play2Grey.png
    - assets/fonts/SigmarOne-Regular.ttf
    - assets/images/background/trees/frames/frame_00_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_01_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_02_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_03_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_04_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_05_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_06_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_07_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_08_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_09_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_10_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_11_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_12_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_13_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_14_delay-0.07s.gif
    - assets/images/background/trees/frames/frame_15_delay-0.07s.gif
    - assets/images/duck/frames/frames/frame_0_delay-0.15s.gif
    - assets/images/duck/frames/frames/frame_1_delay-0.15s.gif
    - assets/images/duck/frames/frames/frame_2_delay-0.15s.gif
    - assets/images/duck/frames/frames/frame_3_delay-0.15s.gif
    - assets/images/duck/frames/frames/frame_4_delay-0.15s.gif
    - assets/images/duck/frames/frames/frame_5_delay-0.15s.gif
    - assets/images/duck/frames/frames/frame_6_delay-0.15s.gif
    - assets/images/background/background/frames/frame_00_delay-0.14s.gif
    - assets/images/background/background/frames/frame_01_delay-0.14s.gif
    - assets/images/background/background/frames/frame_02_delay-0.14s.gif
    - assets/images/background/background/frames/frame_03_delay-0.14s.gif
    - assets/images/background/background/frames/frame_04_delay-0.14s.gif
    - assets/images/background/background/frames/frame_05_delay-0.14s.gif
    - assets/images/background/background/frames/frame_06_delay-0.14s.gif
    - assets/images/background/background/frames/frame_07_delay-0.14s.gif
    - assets/images/background/background/frames/frame_08_delay-0.14s.gif
    - assets/images/background/background/frames/frame_09_delay-0.14s.gif
    - assets/images/background/background/frames/frame_10_delay-0.14s.gif
    - assets/images/background/background/frames/frame_11_delay-0.14s.gif
    - assets/images/background/background/frames/frame_12_delay-0.14s.gif
    - assets/images/background/background/frames/frame_13_delay-0.14s.gif
    - assets/images/background/background/frames/frame_14_delay-0.14s.gif
    - assets/images/background/background/frames/frame_15_delay-0.14s.gif
    - assets/images/background/lights/frame_0_delay-0.01s.gif
    - assets/images/background/front/frames/frame_00_delay-0.04s.gif
    - assets/images/background/front/frames/frame_01_delay-0.04s.gif
    - assets/images/background/front/frames/frame_02_delay-0.04s.gif
    - assets/images/background/front/frames/frame_03_delay-0.04s.gif
    - assets/images/background/front/frames/frame_04_delay-0.04s.gif
    - assets/images/background/front/frames/frame_05_delay-0.04s.gif
    - assets/images/background/front/frames/frame_06_delay-0.04s.gif
    - assets/images/background/front/frames/frame_07_delay-0.04s.gif
    - assets/images/background/front/frames/frame_08_delay-0.04s.gif
    - assets/images/background/front/frames/frame_09_delay-0.04s.gif
    - assets/images/background/front/frames/frame_10_delay-0.04s.gif
    - assets/images/background/front/frames/frame_11_delay-0.04s.gif
    - assets/images/background/front/frames/frame_12_delay-0.04s.gif
    - assets/images/background/front/frames/frame_13_delay-0.04s.gif
    - assets/images/background/front/frames/frame_14_delay-0.04s.gif
    - assets/images/background/front/frames/frame_15_delay-0.04s.gif
    - assets/images/duck/frames/frames/jump/frame_0_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_1_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_2_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_3_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_4_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_5_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_6_delay-0.1s.gif
    - assets/images/duck/frames/frames/jump/frame_7_delay-0.1s.gif
    - assets/images/enemies/wolf/tile000.png
    - assets/images/enemies/wolf/tile001.png
    - assets/images/enemies/wolf/tile002.png
    - assets/images/enemies/wolf/tile003.png
    - assets/images/enemies/wolf/tile004.png
    - assets/images/enemies/wolf/tile005.png
    - assets/images/enemies/bat/tile000.png
    - assets/images/enemies/bat/tile001.png
    - assets/images/enemies/bat/tile002.png
    - assets/images/enemies/bat/tile003.png
    - assets/images/enemies/bat/tile004.png
    - assets/images/enemies/bat/tile005.png
    - assets/images/Menu/b_Play2.png
    - assets/images/Menu/b_Restart.png
    - assets/images/Menu/b_Leaderboard.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
